### ISSUE TITLE
안녕하세요, 코드를 참고하다가 Overflow가 날 수 있는 부분을 발견하였습니다.

### ISSUE THREAD

**Issue by exgs** [365kim/Algorithm_Study_with_jko#1]
안녕하세요, 42-algorithm을 공부하고 있는 학생입니다.
Deque backjoon_1021 문제가 잘 풀리지않아서 고생을 해서 겨우 다 풀고나서,  
365kim님의 코드가 이전부터 깔끔하다고 생각을 했었기 때문에 참고를 하기위해서 코드를 보았는데요  
전역 변수로 `int deque[300]` 크기 300짜리 배열을 두셨는데, 이건 overflow날 수 있지 않나요?
deque_size를 50을 잡고, 중앙에 해당하는 값을 몇번 넣어서 한쪽방향으로만 숫자를 더해주게되면, 300의 크기를  
쉽게 넘어갈수도 있을꺼 같습니다.  

```c
	while (find_size--)
	{
		scanf("%d", &target);
		count += get_route_length();
		printf("idx_front : %d\n",idx_front); // 이 부분을 추가해서 Debugging
	}
	printf("%d\n", count);
```

![캡처_2020_06_06_21_58_04_810](https://user-images.githubusercontent.com/56223639/83944749-d00b5b80-a840-11ea-9542-43bdb071a2f8.png)

365kim님의 code를 실행시켰을 때, 245 이후로 급격하게 idx front 값이 떨어지는 것이 확인 됩니다.  
제 경우는 위 예시에서 220이 나옵니다.  
어쩌다보니 제멋대로 코드리뷰(?)를 하게되었는데요. 도움이 되셨으면 좋겠습니다🙂

**Comment by 365kim** [comment]
exgs님 안녕하세요
우선 코드리뷰 감사드립니다.


올려주신 케이스 돌려보니 바로 세그폴트 발생하네요 ㅜ_ㅜ
문제 풀 당시 덱의 크기가 300이면 넉넉하다고 잘못 판단했습니다. 지적해주셔서 감사합니다.

문제에서 제시한 최대치인 크기 50에 50번의 연산을 수행할 경우에
말씀해주신 것처럼 중앙 쪽에 있는 숫자로 넣어주면
한번에 25칸 이하로 움직일 것이고
50번의 연산 모두 모두 한쪽으로 쏠려서 움직이는 극단적인 케이스를 고려해서,
덱의 크기를 25칸 * 50번 * 2(좌우) = 2500 로, 시작 인덱스를 1250으로 [__변경__ ](https://github.com/365kim/algorithm_study/blob/master/04_deque/2_baekjoon/baekjoon_01021_rotating_queue.c)하였습니다.



좋은 지적 다시한번 감사드립니다 😄
